import type { NextPage } from 'next';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import SearchBar from '../components/SearchBar';

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>GitHub Search Lite</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center justify-start h-screen duration-300 bg-white-one dark:bg-darker-navy lg:justify-center">
        <div className="flex flex-col w-full gap-2 p-6 lg:max-w-[730px]">
          <Navbar />
          <SearchBar />
        </div>
      </main>
    </div>
  );
};

export default Home;
